[BACKLOG-12634] Mavenize pdi-palo-core
pentaho/pdi-palo-core pull request #7
Opened 2017-06-20 20:28 UTC by Kyrrui

2017-06-20 20:37 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-06-21 09:11 UTC, tmcsantos requested changes

2017-06-21 09:11 UTC, tmcsantos commented on pom.xml
> +  <version>2.0.4</version>
this version is too old, should be 8.0-SNAPSHOT

2017-06-21 09:11 UTC, tmcsantos commented on pom.xml
> +        <version>8.0-SNAPSHOT</version>
dependencies versions should be defined as properties, in this special case define a `kettle.version` property

2017-06-21 09:11 UTC, tmcsantos commented on pom.xml
> +      <version>1.2.16</version>
add `log4j.version`property

2017-06-21 09:11 UTC, tmcsantos commented on pom.xml
> +      <version>1.0.73</version>
change to property

2017-06-21 09:11 UTC, tmcsantos commented on pom.xml
> +      <version>4.12</version>
change to property

2017-06-21 13:01 UTC, smaring reviewed
just another tip:  by convention, we usually work on feature branches named after the ticket we are using, in this case BACKLOG-12634, not master.  This makes it easier for others to add your remote, check out your branch, and not have to worry about confusing it with the upstream pentaho master

2017-06-21 13:06 UTC, smaring commented
Also, you need to delete build-res, libext, .classpath, build.properties, build.xml, ivy.xml, and ivysettings.xml.  Leave no trace of the prior build setup.

2017-06-21 13:08 UTC, smaring commented
other than that, and what Tiago commented, it looks like the resultant jar is in good shape by comparison https://image.prntscr.com/image/6Ffu7g1uRC2ciwwFRM2a7g.png

2017-06-21 18:57 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-06-21 19:06 UTC, tmcsantos approved these changes

2017-06-22 17:47 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-06-22 17:57 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-06-26 15:11 UTC, merged